/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package piu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicOptionPaneUI;

/**
 *
 * @author Dalay
 */
public class FazerLogin extends javax.swing.JFrame {

    /**
     * Creates new form FazerLogin
     */
    public FazerLogin() {
        initComponents();
        button_FazerLogin.setEnabled(false);
    }
    
    static String nome; 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_FazerLogin = new javax.swing.JLabel();
        button_Inicio = new javax.swing.JButton();
        button_Cardapio = new javax.swing.JButton();
        button_FazerLogin = new javax.swing.JButton();
        button_Contato = new javax.swing.JButton();
        label_Usuario = new javax.swing.JLabel();
        label_Senha = new javax.swing.JLabel();
        text_UsuarioCliente = new javax.swing.JTextField();
        button_LoginCliente = new javax.swing.JButton();
        button_CadastrarCliente = new javax.swing.JButton();
        passwordfield_SenhaCliente = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_FazerLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        label_FazerLogin.setText("Fazer Login");

        button_Inicio.setText("Inicio");

        button_Cardapio.setText("Cardápio");

        button_FazerLogin.setText("Fazer Login");

        button_Contato.setText("Contato");

        label_Usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_Usuario.setText("Usuário:");

        label_Senha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_Senha.setText("Senha:");

        text_UsuarioCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        button_LoginCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_LoginCliente.setText("Login");
        button_LoginCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_LoginClienteActionPerformed(evt);
            }
        });

        button_CadastrarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_CadastrarCliente.setText("Cadastre-se");

        passwordfield_SenhaCliente.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(label_FazerLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_Inicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_Cardapio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_FazerLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_Contato))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(label_Senha)
                                            .addComponent(label_Usuario))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(passwordfield_SenhaCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_UsuarioCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(button_LoginCliente)
                                        .addGap(65, 65, 65)
                                        .addComponent(button_CadastrarCliente)
                                        .addGap(32, 32, 32)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label_FazerLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Inicio)
                    .addComponent(button_Cardapio)
                    .addComponent(button_FazerLogin)
                    .addComponent(button_Contato))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Usuario)
                    .addComponent(text_UsuarioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Senha)
                    .addComponent(passwordfield_SenhaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_LoginCliente)
                    .addComponent(button_CadastrarCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_LoginClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LoginClienteActionPerformed
        // TODO add your handling code here:
        String value1 = text_UsuarioCliente.getText(); 
        char[] value2 = passwordfield_SenhaCliente.getPassword();
        char[] value3 = value2;
        String value4 = value1; 
        nome = value1; 
        
        if ((value1 == value4) && (value2 == value3)) {
            BemVindoCliente page = new BemVindoCliente();
            page.setVisible(true);
            this.dispose();
        } else {
            System.out.println("enter the valid username and password");
            JOptionPane.showMessageDialog(this, "Usuário ou senha incorreto",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button_LoginClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FazerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FazerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FazerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FazerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FazerLogin().setVisible(true);
            }
        });
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_CadastrarCliente;
    private javax.swing.JButton button_Cardapio;
    private javax.swing.JButton button_Contato;
    private javax.swing.JButton button_FazerLogin;
    private javax.swing.JButton button_Inicio;
    private javax.swing.JButton button_LoginCliente;
    private javax.swing.JLabel label_FazerLogin;
    private javax.swing.JLabel label_Senha;
    private javax.swing.JLabel label_Usuario;
    private javax.swing.JPasswordField passwordfield_SenhaCliente;
    private javax.swing.JTextField text_UsuarioCliente;
    // End of variables declaration//GEN-END:variables
}
