/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package piu;

import sun.tools.jar.Main;

/**
 *
 * @author felipe
 */
public class BemVindoCliente extends javax.swing.JPanel {

    /**
     * Creates new form BemVindoCliente
     */
    public BemVindoCliente() {
        initComponents();
    }
    
    public static void main(String args[]){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_Inicio = new javax.swing.JButton();
        button_Cardapio = new javax.swing.JButton();
        button_FazerLogout = new javax.swing.JButton();
        button_Contato = new javax.swing.JButton();
        label_BemVindoCliente = new javax.swing.JLabel();
        label_Cliente = new javax.swing.JLabel();
        button_FinalizarCompra = new javax.swing.JButton();
        button_EscolherOutroPrato = new javax.swing.JButton();
        button_AcompanharPedido = new javax.swing.JButton();
        button_PedidoRealizados = new javax.swing.JButton();

        button_Inicio.setText("Início");
        button_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_InicioActionPerformed(evt);
            }
        });

        button_Cardapio.setText("Cardápio");

        button_FazerLogout.setText("Fazer Logout");

        button_Contato.setText("Contato");

        label_BemVindoCliente.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        label_BemVindoCliente.setText("Bem vindo ");

        label_Cliente.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        button_FinalizarCompra.setText("Finalizar Fechar Compra");

        button_EscolherOutroPrato.setText("Escolher outro prato");

        button_AcompanharPedido.setText("Acompanhar pedido");

        button_PedidoRealizados.setText("Pedidos realizados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_Inicio)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_BemVindoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_Cardapio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_FazerLogout))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button_FinalizarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_EscolherOutroPrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_AcompanharPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(button_PedidoRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_Contato)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_BemVindoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(label_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Inicio)
                    .addComponent(button_Cardapio)
                    .addComponent(button_FazerLogout)
                    .addComponent(button_Contato))
                .addGap(18, 18, 18)
                .addComponent(button_FinalizarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_EscolherOutroPrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_AcompanharPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_PedidoRealizados)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_InicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_InicioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_AcompanharPedido;
    private javax.swing.JButton button_Cardapio;
    private javax.swing.JButton button_Contato;
    private javax.swing.JButton button_EscolherOutroPrato;
    private javax.swing.JButton button_FazerLogout;
    private javax.swing.JButton button_FinalizarCompra;
    private javax.swing.JButton button_Inicio;
    private javax.swing.JButton button_PedidoRealizados;
    private javax.swing.JLabel label_BemVindoCliente;
    private javax.swing.JLabel label_Cliente;
    // End of variables declaration//GEN-END:variables
}
